In [3]:
import numpy as np 

a = np.array([10,20,30,40])
b = np.array([1,2,3,4])

print(a+b)
print(a*b)
print(a // b)
print(a - b)

[11 22 33 44]
[ 10  40  90 160]
[10 10 10 10]
[ 9 18 27 36]


In [4]:
a = np.array([1,2,3,4])
print(a*2)

[2 4 6 8]


In [7]:
arr = np.array([[1,2,3],[4,5,6]])
print(arr * 5)

[[ 5 10 15]
 [20 25 30]]


In [9]:
arr = np.array([4,8,15,23,42])

print(np.sum(arr))
print(np.mean(arr))
print(np.min(arr))
print(np.max(arr))
print(np.std(arr))
print(np.var(arr))

92
18.4
4
42
13.45511055324333
181.04000000000002


In [10]:
data = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [17]:
print(np.sum(data, axis=1))
print(np.sum(data,axis=0))

[ 6 15 24]
[12 15 18]
