In [2]:
import numpy as np 

a = [1,2,3,4]

arr = np.array(a)
print(arr)

[1 2 3 4]


In [5]:
print(np.array([1,2,3]))
arr

[1 2 3]


array([1, 2, 3, 4])

In [6]:
a = [[1,2,3],[4,5,6],[7,8,9]]
arr = np.array(a)
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [3]:
np.ones([5,8])

array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

In [4]:
np.full([5,5],7)

array([[7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7]])

In [7]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [10]:
np.linspace(1,10,10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [11]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [12]:
np.random.rand(2,3)

array([[0.06964743, 0.18095509, 0.44271452],
       [0.80392093, 0.97057491, 0.5041396 ]])

In [16]:
np.random.randint(1,10,[3,4])

array([[7, 2, 2, 7],
       [8, 1, 9, 1],
       [3, 2, 3, 8]])

In [18]:
arr = np.random.randn(2,4)
arr

array([[ 0.32001217,  0.8965024 ,  0.89430882, -0.32469129],
       [-0.14304777,  0.19072164,  0.94215281,  0.42357368]])