In [5]:
import numpy as np 
arr = np.array([[1,2,3],[4,5,6]])
print(arr.shape)
print(arr.ndim)
print(arr.size)
print(arr.dtype)

(2, 3)
2
6
int64


In [7]:
arr = np.array([1,2,3,4,5])
print(arr[0])
print(arr[-3])


1
3


In [8]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [10]:
arr[0]

array([1, 2, 3])

In [12]:
arr[0,0]

np.int64(1)

In [14]:
a = np.array([1,2,3,4,5])
print(a[:3])

[1 2 3]


In [16]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr[0:2,0:2]
arr[1:,1:]

array([[5, 6],
       [8, 9]])

In [18]:
arr = np.array([5,10,20,30,40])
print(arr>12)
print(arr[arr>12])

[False False  True  True  True]
[20 30 40]


In [21]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]]) 

print(arr[arr>3])

[4 5 6 7 8 9]


In [25]:
a = np.arange(1,31).reshape(6,5)

In [26]:
a.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])