In [5]:
import numpy as np 
arr = np.array([10,20,30,40,50,60])

arr[[0,2,4]]

array([10, 30, 50])

In [12]:
matrix = np.arange(1,13).reshape(3,4)
print(matrix)
matrix[[0,1],[1,2]]

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


array([2, 7])

In [18]:
arr = np.array([5,12,18,7,30])

arr[arr > 10]
np.where(arr > 10,arr,0)

array([ 0, 12, 18,  0, 30])

In [19]:
arr = np.array([3,5,7,8,1,2])
np.sort(arr)

array([1, 2, 3, 5, 7, 8])

In [20]:
np.argsort(arr)

array([4, 5, 0, 1, 2, 3])

In [21]:
a = np.array([1,2,3])
b = np.array([4,5,6])

np.concat([a,b])

array([1, 2, 3, 4, 5, 6])

In [24]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])

np.vstack((b,a))

array([[5, 6],
       [7, 8],
       [1, 2],
       [3, 4]])

In [26]:
np.hstack((b,a))

array([[5, 6, 1, 2],
       [7, 8, 3, 4]])

In [27]:
np.concat((a,b))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])