In [4]:
import numpy as np 

arr = np.array([1,2,3,4,5])

print(type(arr))

<class 'numpy.ndarray'>


In [5]:
a = np.array([1,2,3])
b = np.array([4,5,6])

print( a + b ) 

[5 7 9]


In [6]:
arr = np.array([
    [1,2,3],
    [4,5,6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [7]:
arr = np.array([
    [
        [1,2],
        [3,4]
    ], 
    [
        [5,6],
        [7,8]
    ]
])
print(arr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [9]:
arr = np.array([
    [1,2,3],
    [4,5,6]
])
print(arr.shape)

arr = np.array([1,2,3,4])
print(arr.shape)

(2, 3)
(4,)


In [12]:
arr = np.array([
    [1,2],
    [3,4]
])
print(arr.ndim)
print(arr.size)
print(arr.dtype)

2
4
int64


In [13]:
arr = np.zeros((2,3))
print(arr)

[[0. 0. 0.]
 [0. 0. 0.]]


In [15]:
arr = np.ones((3,2))
print(arr)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [17]:
arr = np.arange(1,10)
print(arr)


[1 2 3 4 5 6 7 8 9]


In [18]:
arr = np.arange(0,20,2)
print(arr)

[ 0  2  4  6  8 10 12 14 16 18]


In [20]:
arr = np.linspace(0,1,5)
print(arr)

[0.   0.25 0.5  0.75 1.  ]


In [21]:
arr = np.eye(3)
print(arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [23]:
arr = np.array([10,20,30,40,50])
print(arr[0])
print(arr[-1])

10
50


In [27]:
print(arr[1:4])
print(arr[:3])
print(arr[2:])
print(arr[::-1])

[20 30 40]
[10 20 30]
[30 40 50]
[50 40 30 20 10]


In [39]:
arr = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
print(arr[1,2])
print(arr[1])
print(arr[:,1])
print(arr[:2])
print(arr[:, :2])
print(arr[0:2, 1:3])
arr = np.array([10,20,30,40,50])
print(arr > 25)
print(arr[arr>25])
print(arr[(arr > 20) & ( arr < 50)])

6
[4 5 6]
[2 5 8]
[[1 2 3]
 [4 5 6]]
[[1 2]
 [4 5]
 [7 8]]
[[2 3]
 [5 6]]
[False False  True  True  True]
[30 40 50]
[30 40]


In [44]:
arr = np.array([10,20,30,40,50])
print(arr[[0,2,4]])

[10 30 50]


In [45]:
marks = np.array([35,90, 78,40,99,20])
print(marks[marks >= 40])

[90 78 40 99]
