In [1]:
import numpy as np 

arr = np.array([1,2,3,4,5])

print(type(arr))

<class 'numpy.ndarray'>


In [5]:
a = np.array([1,2,3])
b = np.array([4,5,6])

print( a + b ) 

[5 7 9]


In [6]:
arr = np.array([
    [1,2,3],
    [4,5,6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [7]:
arr = np.array([
    [
        [1,2],
        [3,4]
    ], 
    [
        [5,6],
        [7,8]
    ]
])
print(arr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [9]:
arr = np.array([
    [1,2,3],
    [4,5,6]
])
print(arr.shape)

arr = np.array([1,2,3,4])
print(arr.shape)

(2, 3)
(4,)


In [12]:
arr = np.array([
    [1,2],
    [3,4]
])
print(arr.ndim)
print(arr.size)
print(arr.dtype)

2
4
int64


In [13]:
arr = np.zeros((2,3))
print(arr)

[[0. 0. 0.]
 [0. 0. 0.]]


In [15]:
arr = np.ones((3,2))
print(arr)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [17]:
arr = np.arange(1,10)
print(arr)


[1 2 3 4 5 6 7 8 9]


In [18]:
arr = np.arange(0,20,2)
print(arr)

[ 0  2  4  6  8 10 12 14 16 18]


In [20]:
arr = np.linspace(0,1,5)
print(arr)

[0.   0.25 0.5  0.75 1.  ]


In [21]:
arr = np.eye(3)
print(arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [23]:
arr = np.array([10,20,30,40,50])
print(arr[0])
print(arr[-1])

10
50


In [27]:
print(arr[1:4])
print(arr[:3])
print(arr[2:])
print(arr[::-1])

[20 30 40]
[10 20 30]
[30 40 50]
[50 40 30 20 10]


In [39]:
arr = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
print(arr[1,2])
print(arr[1])
print(arr[:,1])
print(arr[:2])
print(arr[:, :2])
print(arr[0:2, 1:3])
arr = np.array([10,20,30,40,50])
print(arr > 25)
print(arr[arr>25])
print(arr[(arr > 20) & ( arr < 50)])

6
[4 5 6]
[2 5 8]
[[1 2 3]
 [4 5 6]]
[[1 2]
 [4 5]
 [7 8]]
[[2 3]
 [5 6]]
[False False  True  True  True]
[30 40 50]
[30 40]


In [44]:
arr = np.array([10,20,30,40,50])
print(arr[[0,2,4]])

[10 30 50]


In [45]:
marks = np.array([35,90, 78,40,99,20])
print(marks[marks >= 40])

[90 78 40 99]


In [48]:
arr = np.array([1,2,3,4])
print(arr * 2)

[2 4 6 8]


In [4]:
a = np.array([1,2,3])
b = np.array([10,20,30])
print( a + b)
print(b - a)
print(a * b)
print(b / a)
print(a ** 2)

[11 22 33]
[ 9 18 27]
[10 40 90]
[10. 10. 10.]
[1 4 9]


In [5]:
arr = np.array([1, 4, 9, 16])

print(np.sqrt(arr))

[1. 2. 3. 4.]


In [6]:
arr = np.array([1, 2, 3])

print(arr + 5)

[6 7 8]


In [7]:
arr = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

print(arr + 10)

[[11 12 13]
 [14 15 16]]


In [9]:
matrix = np.array([
    [1,2,3],
    [4,5,6]
])
vector = np.array([10,20,30])
print(matrix + vector )

[[11 22 33]
 [14 25 36]]


In [2]:
sales = np.array([
    [100,200, 300], 
    [400,500,600]
])

bonus = np.array([10,20,30])
print(sales + bonus)

[[110 220 330]
 [410 520 630]]


In [7]:
arr = np.array([1,2,3,4,5,6])
print(arr)
new_arr = arr.reshape(2,3)
print(new_arr)
print(arr.reshape(2,-1))
print(arr.reshape(-1,1))

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [12]:
arr = np.array([
    [1,2,3],
    [4,5,6]
])
flat = arr.flatten()
print(flat)
print(arr)

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]


In [11]:
arr = np.array([
    [1,2],
    [3,4]
])

r = arr.ravel()
r[0] = 100 
print(arr)

[[100   2]
 [  3   4]]


In [13]:
arr = np.array([
    [1,2,3],
    [4,5,6]
    ])
print(arr.T)

[[1 4]
 [2 5]
 [3 6]]


In [16]:
arr = np.array([
    [1,2,3],
    [4,5,6]
])
print(arr.sum(axis=0))
print(arr.sum(axis=1))

[5 7 9]
[ 6 15]


In [18]:
marks = np.array([
    [80,90,70],
    [60,75,85],
    [88,92,95]
])
print(marks.sum(axis=0))

[228 257 250]


In [29]:
import numpy as np

sales = np.array([120, 340, 560, 230, 890, 450])
print(sales.sum())
print(sales.mean())
print(np.median(sales))
print(sales.min())
print(sales.max())
print(sales.argmax())
print(sales.argmin())
print(sales.std())
print(sales.var())
print(np.sort(sales))
print(np.sort(sales)[::-1])

2590
431.6666666666667
395.0
120
890
4
0
249.3602926601498
62180.55555555556
[120 230 340 450 560 890]
[890 560 450 340 230 120]


In [30]:
arr = np.array([1,2,2,3,4,4,5])

print(np.unique(arr))

[1 2 3 4 5]


In [33]:
sales = np.array([120, 340,560,230,890,450])
print(sales[sales > 400])
print(sales[(sales > 200) & (sales < 600)])

[560 890 450]
[340 560 230 450]


In [34]:
arr = np.array([10,20,30,40])

print(np.where(arr > 25))

(array([2, 3]),)


In [36]:
arr = np.array([10,20,30,40])
result = np.where(arr > 25 , "Hight", "Low")
print(result)

['Low' 'Low' 'Hight' 'Hight']


In [39]:
data = np.array([10,20,np.nan,40])
print(np.isnan(data))
print(np.nanmean(data))
print(np.nan_to_num(data))

[False False  True False]
23.333333333333332
[10. 20.  0. 40.]


In [40]:
marks = np.array([
    [80,90,70],
    [60,75,85],
    [88,92,95]
])
print(marks.mean(axis=1))

[80.         73.33333333 91.66666667]


In [8]:
print(np.random.rand())
print(np.random.rand(5))
print(np.random.rand(2,3))
print(np.random.randint(1,10))
print(np.random.randint(1,100,5))
print(np.random.randint(1,50,(3,4)))

0.30678453166509956
[0.68066691 0.2942079  0.2941557  0.6009467  0.60631938]
[[0.4820938  0.0837034  0.78350129]
 [0.98810003 0.27197432 0.65031481]]
2
[71 86 81 27 68]
[[36 23 44 41]
 [ 4 34 32  6]
 [16 26  8 49]]


In [9]:
print(np.random.randn(5))

[ 1.85904194  0.07221781  0.04841101 -0.28724386 -0.52601041]


In [11]:
arr = [10,20,30,40]
print(np.random.choice(arr))
print(np.random.choice(arr,3))

30
[10 40 40]


In [15]:
arr = ["Win", "Lose"]

print(np.random.choice(arr, p=[0.8,0.2]))

Win


In [16]:
arr = np.array([1,2,3,4,5])

np.random.shuffle(arr)

print(arr)

[3 2 5 1 4]


In [18]:
np.random.seed(42)
print(np.random.randint(1,100,5))

[52 93 15 72 61]


In [19]:
data = np.array([1,2,3,4,5,6])

np.random.shuffle(data)

print(data)


[6 1 4 3 2 5]
